#:schema node_modules/wrangler/config-schema.json
name = "xyz"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"
experimental_serve_directly = true

[observability]
enabled = true

[[routes]]
pattern = "xyzdomaingenerator.xyz"
custom_domain = true

[[routes]]
pattern = "www.xyzdomaingenerator.xyz"
custom_domain = true

[[kv_namespaces]]
binding = "xyz"
id = "d4f8926d840e429ba46812e749cdf691"
